name: toolify
description: "A open source toolkit app"
publish_to: "none"
home: https://gokeihub.blogspot.com/

version: 1.0.2+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  image_picker: ^1.1.2
  http: ^1.2.2
  hexcolor: ^3.0.1
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  icons_launcher: ^3.0.0
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  barcode_widget: ^2.0.4
  url_launcher: ^6.3.0
  pdf: ^3.11.1
  package_info_plus: ^8.0.2
  # image_gallery_saver: ^2.0.3
  flutter_image_compress: ^2.3.0
  printing: ^5.13.3
  system_info2: ^4.0.0
  flutter_markdown: ^0.7.3+2
  connectivity_plus: ^6.0.5
  path_provider: ^2.1.4
  battery_plus: ^6.0.3
  quick_actions: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  screenshot: ^3.0.0
  device_info_plus: ^10.1.2
  image_gallery_saver_plus: ^3.0.5

  # cupertino_icons: ^1.0.6
  # flutter_lints: ^4.0.0
  # image_picker: ^1.1.2
  # http: ^1.2.2
  # hexcolor: ^3.0.1
  # cached_network_image: ^3.4.1
  # auto_size_text: ^3.0.0
  # icons_launcher: ^2.1.7
  # flutter_dotenv: ^5.1.0
  # shared_preferences: ^2.3.2
  # barcode_widget: ^2.0.4
  # intl: ^0.19.0
  # url_launcher: ^6.3.0
  # package_info_plus: ^8.0.2
  # screenshot: ^3.0.0
  # # image_gallery_saver: ^2.0.3
  # pdf: ^3.11.1
  # printing: ^5.13.2
  # quick_actions: ^1.0.7
  # flutter_image_compress: ^2.3.0
  # path_provider: ^2.1.4
  # flutter_staggered_grid_view: ^0.7.0
  # device_info_plus: ^10.1.2
  # battery_plus: ^6.0.3
  # system_info2: ^4.0.0
  # # torch_light: ^1.1.0
  # connectivity_plus: ^6.0.5
  # flutter_markdown: ^0.7.3+1
  # font_awesome_flutter: ^10.7.0
  # image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/app_icon-removebg.png
    - .env
    - CHANGELOG.md
